version: '3.8'

x-app-service: &default-app
  build: .
  command: ''
  environment:
    - MONGO_URL=mongodb://mongo:27017/dev
    - TYPEORM_HOST=mysql
    - TYPEORM_USERNAME=root
    - TYPEORM_PASSWORD=root
    - ELASTICSEARCH_URL=http://192.168.1.46:9200
    - ELASTICSEARCH_HOSTS=http://192.168.1.46:9200
  depends_on:
    - mongo
    - kibana
    - elasticsearch
    - mysql
  volumes:
    - .:/code:delegated
    - node_modules:/code/node_modules:delegated

services:
  app:
    <<: *default-app

  mooc-backend:
    <<: *default-app
    command: bash -c "npm run build && npm run start:mooc:backend"
    ports:
      - 3000:3000

  backoffice-frontend:
    <<: *default-app
    command: bash -c "npm run build && npm run start:backoffice:frontend"
    ports:
      - 8032:8032

  backoffice-backend:
    <<: *default-app
    command: bash -c "npm run build && npm run start:backoffice:backend"
    ports:
      - 3001:3000

  art-backend:
    <<: *default-app
    command: bash -c "npm run build && npm run dev:art:backend"
    ports:
      - 3002:3000

  mongo:
    image: mongo:3.4.6
    volumes:
      - ./data/mongo:/data/db:delegated
    ports:
      - 27017:27017

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: codely-elasticsearch
    environment:
      - node.name=codely-elasticsearch
      - discovery.type=single-node #Elasticsearch forms a single-node cluster
      - bootstrap.memory_lock=true # might cause the JVM or shell session to exit if it tries to allocate more memory than is available!
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1 # The memlock soft and hard values configures the range of memory that ElasticSearch will use. Setting this to –1 means unlimited.
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'

  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.1
    container_name: codely-kibana
    environment:
      ELASTICSEARCH_URL: http://codely-elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://codely-elasticsearch:9200
    ports:
      - 5601:5601

  rabbitmq:
    image: 'rabbitmq:3.8-management'
    ports:
      - 5672:5672
      - 15672:15672

  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: art
      MYSQL_USER: art
      MYSQL_PASSWORD: art
    ports:
      - "3309:3306"

volumes:
  node_modules:
  mysql_data:
  esdata:
    driver: local
